name: CI

on:
  pull_request:
  push:
    branches: [master, main]
    tags: ["*"]

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        java: [adopt@1.8, adopt@1.11]
        scala: [2.12.12, 2.13.5]
        arangodb: [3.6.12, 3.7.9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Cache scala dependencies
        uses: coursier/cache-action@v6

      - name: Run tests
        run: sbt ++${{ matrix.scala }} -Dtest.arangodb.version=${{ matrix.arangodb }} coverage test

      - name: Coverage aggregation
        run: sbt ++${{ matrix.scala }} coverageAggregate

      - name: Coverage upload
        uses: codecov/codecov-action@v1
        with:
          flags: scala-${{ matrix.scala }}

  release:
    if: github.event_name == 'push'
    needs: [test]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10

      - name: Cache scala dependencies
        uses: coursier/cache-action@v6

      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}