name: CI

on:
  pull_request:
    paths-ignore:
      - site/**
  push:
    branches: [master, main]
    tags: ["*"]
    paths-ignore:
      - site/**

jobs:

  test:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: ['8', '11', '17']
        scala: [2.13.10, 3.3.0]
        arangodb: [3.9.10, 3.10.6]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'sbt'

      - name: Run tests
        run: sbt ++${{ matrix.scala }} -Dtest.arangodb.version=${{ matrix.arangodb }} coverage test

      - name: Coverage aggregation
        run: sbt ++${{ matrix.scala }} coverageAggregate

      - name: Coverage upload
        uses: codecov/codecov-action@v3
        with:
          flags: scala-${{ matrix.scala }}

  release:
    if: github.event_name == 'push'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'

      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}