name: Site

on:
  push:
    branches: [master, main]
    paths:
      - .github/workflows/site.yml
      - site/**

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  publish:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/site/Gemfile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install jekyll binstub
        run: bundle binstubs jekyll --path=$HOME/.local/bin

      - name: Compose up
        run: docker-compose -f site/docker-compose.yml up -d

      - name: Build site
        run: sbt site/makeMicrosite

      - name: Compose down
        run: docker-compose -f site/docker-compose.yml down

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/target/site