name: Site

on:
  push:
    branches: [master, main]
    paths:
      - .github/workflows/site.yml
      - site/**

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10

      - name: Cache scala dependencies
        uses: coursier/cache-action@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Compose up
        run: docker-compose -f site/docker-compose.yml up -d

      - name: Build site
        run: sbt site/publishMicrosite

      - name: Compose down
        run: docker-compose -f site/docker-compose.yml down
